### ISSUE TITLE
Quick navigation

### ISSUE THREAD

**Issue by ashiklom** [mattn/calendar-vim#29]
Great package! I happily use it to help me navigate my vimwiki diary entries.

Just a suggested feature, inspired by the `itchyny/calendar.vim` plugin -- quickly navigating between dates using the `h` and `l` keys. I implemented this in my own `.vimrc` somewhat clumsily as follows:

```
au FileType calendar nmap <buffer> l /\( \\|\d\)\d\(+\\|*\\| \)<CR>:noh<CR>
au FileType calendar nmap <buffer> h lNN:noh<CR>
```

Maybe you (or somebody) can build this in as an option into your package, with a cleaner implementation?

**Comment by mattn** [comment]
Thank you. But It is not necessarily the case that all of users want this behavior. So please put it on your vimrc.
