### ISSUE TITLE
Question: How do you set the width of the calendar-vim window

### ISSUE THREAD

**Issue by dbhaig** [mattn/calendar-vim#31]
When I open calendar-vim in vimwiki, it opens such that it is too narrow to display all of the columns. Is there a configuration variable that I can set in my .vimrc file to correct this?

Thanks

**Comment by mattn** [comment]
could you please paste screenshot here?

**Comment by dbhaig** [comment]
![screenshot from 2017-03-06 23 26 04](https://cloud.githubusercontent.com/assets/10187339/23641797/9ad76e60-02c4-11e7-8e37-5dc49936ecf1.png)

**Comment by mattn** [comment]
It seems that some plugin forcibly set width of calendar.vim. calendar.vim open the buffer with specified width.

**Comment by dbhaig** [comment]
Do you have any suggestions as to how to find the source of the problem?

**Comment by mattn** [comment]
Please let me known how to reproduce.

**Comment by dbhaig** [comment]
After some more investigation, the problem occurs when I configure vim to use relative line numbering. 
That is, I have the following setting in my .vimrc file: 
                          
set relativenumber

Not sure why, but this seems to be the source of the issue

**Comment by mattn** [comment]
try to add `nornu` to `g:calendar_options` if you have setting `g:calendar_options`.

**Comment by dbhaig** [comment]
Adding the following line to my .vimrc file seems to have resolved the issue:

let g:calendar_options = 'nornu'

Thank you very much for your help.
