### ISSUE TITLE
[Question/Request] Highlight days with a diary note in bold font

### ISSUE THREAD

**Issue by mgarort** [mattn/calendar-vim#48]
Hi,

First of all, thanks a lot for calendar-vim! I use it together with the vimwiki diary and it is very useful.

calendar-vim marks days with an associated diary note with a plus sign `+`; it marks weekends in **bold font**; and it marks the current day with an asterisk `*`.

Is it possible to change this format? The `+` and `*` signs clutter my calendar window, making it hard to distinguish which days have notes and which don't at a first glance. I would prefer to mark days with a diary note in **bold**, and to not mark weekends as special days.

Thanks a lot in advance.

**Comment by hotoo** [comment]
I'm disagree your opinion. I think the plus sign is very clear to show which day has diary note.

![image](https://user-images.githubusercontent.com/143572/152164842-274887e6-b87a-4b8c-9183-e92f016ef8ae.png)

**Comment by mgarort** [comment]
@hotoo thank you for your comment. However, this is clearly a matter of personal opinion so you can have a different opinion and my point is still valid. Also, please note that the reason why in your calendar it is clear which days have diary notes or not may not be the plus sign `+`, but rather the fact that they are colored differently. See how it looks in a different color palette:

![screenshot](https://user-images.githubusercontent.com/26173140/152307912-e8f9b746-320d-4008-9baf-ab438fe26844.png)

If you have experience with the source code of `calendar-vim` and could let me know how to change the highlighting of the days with a calendar view, please let me know! I would be very grateful :)

**Comment by hotoo** [comment]
@mgarort I'm use my custom colorscheme which modified from [manuscript](https://github.com/hotoo/vimrc/blob/master/colors/hotoo_manuscript.vim), and I think you may need config:

```viml
let g:calendar_mark = 'left-fit'            " let plus(+) near the date, like +8.
```

**Comment by mgarort** [comment]
Hi @hotoo , thank you for the `left-fit` suggestion, that is useful.

Regarding `guifg` and `guibg`, those only work in GVim and I use regular terminal Vim, so I'm afraid I can't use those.

**Comment by hotoo** [comment]
You can use ctermbg and ctermfg.

`:help highlight-cterm`

**Comment by mgarort** [comment]
Oh, thank you so much! `ctermbg` works. Now I can mark the days with diary notes with a different colors.

This solves my problem to mark days with diary notes, so I'm closing the issue.
