### ISSUE TITLE
Filename became directory

### ISSUE THREAD

**Issue by hoaxdream** [mattn/calendar-vim#50]
Hi sir, my when i do `:Calendar` and pick a date, the file name is written as directory like this: `/diary/2022/03/17.md`

here is my configuration:
```
vim.g.calendar_diary = "~/.config/dev/personal/diary"
```
Expected result: `/diary/2022-03-17.md`

**Comment by hotoo** [comment]
https://github.com/mattn/calendar-vim/pull/44 PR is not merged, but you can use https://github.com/hotoo/calendar-vim and config in vimrc:

```viml
Plug 'hotoo/calendar-vim'
let g:calendar_diary_path_pattern = '{YYYY}-{MM}-{DD}{EXT}'
```
