### ISSUE TITLE
Add Command to Jump to next/prev Calendar Entry 

### ISSUE THREAD

**Issue by ei-eiron** [mattn/calendar-vim#52]
Looking through the help I was wondering if we might add a normal mode command (from the Calendar entry file, not the Calendar) to `jump` to the next and previous day's entry, so one might scan through days as they do through open buffers or through the jump list.

(I'm putting this here in case you think it's worth an enhancement rather than a PR from me, which will probably not happen for some time. If that's inappropriate, please let me know. Thanks!!)

**Comment by hotoo** [comment]
This is feature about your carender entry, not canendar.

You can remap `<C-j>`/`<C-k>` to jump next/prev entry by file path or file name.

**Comment by ei-eiron** [comment]
Thank you @hotoo, that's a good way to look at it. When I touch my mappings next I'll experiment with that.
